services:
  - type: web
    name: task-manager-backend
    env: node
    buildCommand: |
      npm ci
      npx prisma generate
      npx prisma migrate deploy
      npx tsc
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://task-flow-app-six.vercel.app
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: taskmanager-db
    databaseName: taskmanager
    user: taskmanager_user
    plan: free
